# create AWS credentials for CircleCI to use
# the credentials are stored in the CircleCI environment variables
# the creds are used for S3 state persistence
version: '2.1'

orbs:
  terraform: circleci/terraform@3.7.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          name: fmt
          checkout: true
          context: terraform
          path: environments/dev
          recursive: true

      # dev jobs
      
      - terraform/validate:
          name: validate-dev
          checkout: true
          context: terraform
          path: environments/dev
          requires:
            - fmt
          filters:
            branches:
              only: dev

      - terraform/destroy:
          name: destroy-dev-initial
          checkout: true
          context: terraform
          path: environments/dev
          requires:
            - validate-dev
          filters:
            branches:
              only: dev

      - terraform/plan:
          name: plan-dev
          checkout: true
          context: terraform
          persist-workspace: true
          path: environments/dev
          requires:
            - destroy-dev-initial
          filters:
            branches:
              only: dev

      - hold-dev:
          type: approval
          requires:
            - plan-dev
          filters:
            branches:
              only: dev
         
      - terraform/apply:
          name: apply-dev
          attach-workspace: true
          context: terraform
          path: environments/dev
          filters:
            branches:
              only: dev
          requires:
            - hold-dev

# prod jobs
      - terraform/validate:
          name: validate-prod
          checkout: true
          context: terraform
          path: environments/prod
          filters:
            branches:
              only: main
          requires:
            - fmt

      - terraform/plan:
          name: plan-prod
          checkout: true
          context: terraform
          path: environments/prod
          persist-workspace: true
          filters:
            branches:
              only: main
          requires:
            - validate-prod

      - hold-prod:
          type: approval
          requires:
            - plan-prod
          filters:
            branches:
              only: main

#      - terraform/destroy:
#          name: destroy-dev
#          context: terraform
#          path: environments/dev
#          filters:
#            branches:
#              only: main
#          requires:
#            - hold-prod

      - terraform/apply:
          name: apply-prod
          attach-workspace: true
          context: terraform
          path: environments/prod
          filters:
            branches:
              only: main
          requires:
            - hold-prod